#ifndef SCRATCHPAD_GAME_SCRATCHPAD_GAME_H
#define SCRATCHPAD_GAME_SCRATCHPAD_GAME_H

//class ScratchpadGame : QApplication
//{
//protected:
//	
//};

#endif // !SCRATCHPAD_GAME_SCRATCHPAD_GAME_H
#define SCRATCHPAD_GAME_SCRATCHPAD_GAME_H
